### ISSUE TITLE
Error 500 when GET /games

### ISSUE THREAD

**Issue by atto-bit** [The-Microservice-Dungeon/game#75]
timestamp": "2022-01-04T11:22:07.092+00:00",
"status": 500,
"error": "Internal Server Error",

"message": "Null value was assigned to a property [class microservice.dungeon.game.aggregates.game.domain.Game.maxPlayers] of primitive type setter of microservice.dungeon.game.aggregates.game.domain.Game.maxPlayers; nested exception is org.hibernate.PropertyAccessException: Null value was assigned to a property [class microservice.dungeon.game.aggregates.game.domain.Game.maxPlayers] of primitive type setter of microservice.dungeon.game.aggregates.game.domain.Game.maxPlayers",

**Comment by BrokenButler** [comment]
Wie hast du den Error created, Ich kriege den Error bei mir nicht, wenn Ich ein paar Games mache und sie dann abrufe.

**Comment by tobi6112** [comment]
Same Error here. Steps to reproduce by relying on the API Spec:
https://the-microservice-dungeon.github.io/docs/openapi/game#tag/games/paths/~1games/post

1. Start Game Service
2. POST /game
```sh
curl --request POST \
  --url http://localhost:8080/games \
  --header 'Content-Type: application/json' \
  --data '{
  "numberOfRounds": 58,
  "numberOfMaxPlayers": 6
}'
```
3. GET /games
```sh
curl --request GET \
  --url http://localhost:8080/games
```

Probably the Documentation and the Implementations are out of sync, since the property in your implementation is called `maxPlayers` not `numberOfMaxPlayers`.

**Comment by FGrueterich** [comment]
Das mit dem ou of synch ist behoben. Bitte mal schauen, ob der Fehler immer noch aufrtritt.

**Comment by BrokenButler** [comment]
Da ist immernoch ein Typo in der Doc, wenn der da ist wenn ich gleich Zuhause bin immernoch da ist Page ich meinen fix
